version: 2.1  # Xác định phiên bản CircleCI

orbs:
  python: circleci/python@2.2.0  # Orb Python của CircleCI

jobs:
  build_and_test:
    executor: python/default  # Sử dụng executor Python mặc định
    steps:
      - checkout  # Kiểm tra mã nguồn từ Git

      # Cài đặt dependencies từ requirements.txt
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt  # Cài đặt tất cả các thư viện trong requirements.txt

      # Chạy các bài kiểm tra với pytest
      - run:
          name: Run tests
          command: |
            echo "Running tests with pytest..."
            pytest tests/ --maxfail=1 --disable-warnings -v  # Chạy pytest trên thư mục tests

      # Lưu trữ workspace để sử dụng ở các bước tiếp theo
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    executor: python/default  # Sử dụng executor Python mặc định
    steps:
      - checkout  # Kiểm tra mã nguồn từ Git

      # Cài đặt Railway CLI
      - run:
          name: Install Railway CLI
          command: |
            curl -sSL https://railway.app/install.sh | bash  # Cài đặt Railway CLI

      # Đăng nhập vào Railway bằng API key
      - run:
          name: Login to Railway
          command: railway login --apiKey $RAILWAY_API_KEY # Đăng nhập vào Railway bằng API key

      # Triển khai ứng dụng lên Railway
      - run:
          name: Deploy to Railway
          command: |
            railway up --app $RAILWAY_APP_NAME  # Triển khai ứng dụng lên Railway với tên ứng dụng

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build_and_test  # Chạy job build_and_test trước
      - deploy:  # Sau khi build_and_test hoàn thành, chạy job deploy
          requires:
            - build_and_test  # Đảm bảo job deploy chỉ chạy sau khi build_and_test thành công
          filters:
            branches:
              only: circle-ci-start