version: 2.1
orbs:
  python: circleci/python@2.2.0
  heroku: circleci/heroku@2.0.0

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout

      # Cài đặt các dependencies trực tiếp nếu không có tệp requirements.txt
      - run:
          name: Install dependencies
          command: |
            pip install pytest  # Thêm các thư viện bạn cần ở đây

      - run:
          name: Run tests
          command: python -m pytest

      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    executor: python/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: circle-ci-start
