version: 2.1

orbs:
  python: circleci/python@2.2.0

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            echo "Running tests with pytest..."
            pytest tests/ --maxfail=1 --disable-warnings -v

      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    executor: python/default
    steps:
      - checkout

      - run:
          name: Install Railway CLI
          command: |
            curl -sSL https://railway.app/install.sh | bash
     
      - run:
          name: Create .railway directory
          command: mkdir -p ~/.railway

      - run:
          name: Set Railway Token
          command: echo $RAILWAY_API_KEY > ~/.railway/token
      
      - run:
            name: Ensure Railway project is set up
            command: railway link

      - run:
          name: Deploy to Railway
          command: |
            railway up

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: circle-ci-start  # Chỉ chạy workflow này khi có thay đổi trên nhánh circle-ci-start
