version: 2.1

orbs:
  python: circleci/python@2.2.0

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout

      # Cài đặt các dependencies nếu không có requirements.txt
      - run:
          name: Install dependencies
          command: pip install pytest

      - run:
          name: Run tests
          command: |
            echo "Running tests with pytest..."
            pytest tests/ --maxfail=1 --disable-warnings -v

      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Railway CLI
          command: |
            curl -sSL https://railway.app/install.sh | bash

      - run:
          name: Login to Railway
          command: railway login --token $RAILWAY_API_KEY  # Sử dụng API key của bạn

      - run:
          name: Deploy to Railway
          command: |
            railway up --app $RAILWAY_APP_NAME  # Thay thế $RAILWAY_APP_NAME bằng tên app của bạn

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
