version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/my-python-app

jobs:
  install_dependencies:
    executor: python-executor
    steps:
      - checkout  # Lấy mã nguồn từ repo
      - run:
          name: Install dependencies
          command: |
            echo "Start creating virtual environment..."
            python --version  # Kiểm tra phiên bản Python
            pip install --upgrade pip  # Cập nhật pip để tránh lỗi
            pip install -r requirements.txt  # Cài đặt các thư viện trong requirements.txt

  run_tests:
    executor: python-executor
    steps:
      - checkout  # Lấy mã nguồn từ repo
      - run:
          name: Run tests
          command: |
            echo "Checking if virtual environment exists..."
            python --version  # Kiểm tra lại phiên bản Python sau khi kích hoạt môi trường ảo
            python -m unittest test_sample.py

  run_app:
    executor: python-executor
    steps:
      - checkout  # Lấy mã nguồn từ repo
      - run:
          name: Run app.py
          command: |
            echo "Starting app.py..."
            python app.py  # Chạy file app.py (nếu đây là ứng dụng Flask hoặc ứng dụng Python khác)

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - run_app:
          requires:
            - run_tests
          filters:
            branches:
              only: circle-ci-start