version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/my-python-app

jobs:
  install_dependencies:
    executor: python-executor
    steps:
      - checkout  # Lấy mã nguồn từ repo
      - run:
          name: Install dependencies
          command: |
            echo "Creating virtual environment..."
            python -m venv venv  # Tạo môi trường ảo
            ls venv # Kiểm tra xem thư mục venv đã được tạo chưa
            source venv/bin/activate  # Kích hoạt môi trường ảo
            pip install --upgrade pip  # Cập nhật pip để tránh lỗi
            pip install -r requirements.txt  # Cài đặt các thư viện trong requirements.txt

  run_tests:
    executor: python-executor
    steps:
      - checkout  # Lấy mã nguồn từ repo
      - run:
          name: Run tests
          command: |
            ls venv  # Kiểm tra lại thư mục venv
            source venv/bin/activate  # Kích hoạt môi trường ảo
            python -m unittest test_sample.py  # Chạy các bài kiểm tra tự động

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
          filters:
            branches:
              only: circle-ci-start